mbamburova/pa165-wine-cellar

- wine-cellar-persistence/src/main/java/cz/muni/fi/pa165/dao/WineDaoImpl.java
- wine-cellar-persistence/src/main/java/cz/muni/fi/pa165/entity/Packing.java
modify entity Packing, add WineDaoImpl
> modify entity Packing, add WineDaoImpl

- wine-cellar-persistence/src/main/java/cz/muni/fi/pa165/dao/WineDao.java
- wine-cellar-persistence/src/main/java/cz/muni/fi/pa165/dao/WineDaoImpl.java
> add methods to wineDao

- wine-cellar-persistence/src/main/java/cz/muni/fi/pa165/dao/PriceDaoImpl.java
- wine-cellar-persistence/src/main/java/cz/muni/fi/pa165/entity/MarketingEvent.java
- wine-cellar-persistence/src/main/java/cz/muni/fi/pa165/entity/Packing.java
- wine-cellar-persistence/src/main/java/cz/muni/fi/pa165/entity/Price.java
- wine-cellar-persistence/src/main/java/cz/muni/fi/pa165/entity/WineList.java
- wine-cellar-persistence/src/main/resources/META-INF/persistence.xml
- wine-cellar-persistence/src/test/java/cz/muni/fi/pa165/dao/PriceDaoTest.java
> bamburova-working

- wine-cellar-persistence/src/main/java/cz/muni/fi/pa165/dao/WineDao.java
> marketing test ok

- wine-cellar-api/src/main/java/cz/muni/fi/pa165/dto/PackingDto.java
- wine-cellar-api/src/main/java/cz/muni/fi/pa165/dto/PriceDto.java
- wine-cellar-api/src/main/java/cz/muni/fi/pa165/dto/WineListDto.java
- wine-cellar-api/src/main/java/cz/muni/fi/pa165/facade/WineFacade.java
- wine-cellar-persistence/src/main/java/cz/muni/fi/pa165/entity/Packing.java
- wine-cellar-persistence/src/main/java/cz/muni/fi/pa165/entity/Price.java
- wine-cellar-persistence/src/main/java/cz/muni/fi/pa165/entity/Wine.java
- wine-cellar-persistence/src/test/java/cz/muni/fi/pa165/dao/PackingDaoTest.java
- wine-cellar-persistence/src/test/java/cz/muni/fi/pa165/dao/PriceDaoTest.java
> Edit entities and DTOs

- wine-cellar-api/src/main/java/cz/muni/fi/pa165/dto/WineDto.java
- wine-cellar-api/src/main/java/cz/muni/fi/pa165/facade/PackingFacade.java
- wine-cellar-service/pom.xml
- wine-cellar-service/src/main/java/cz/muni/fi/pa165/facade/PackingFacadeImpl.java
- wine-cellar-service/src/main/java/cz/muni/fi/pa165/service/PriceService.java
- wine-cellar-service/src/main/java/cz/muni/fi/pa165/service/PriceServiceImpl.java
- wine-cellar-service/src/test/java/cz/muni/fi/pa165/facade/MarketingEventFacadeTest.java
- wine-cellar-service/src/test/java/cz/muni/fi/pa165/facade/WineListFacadeTest.java
- wine-cellar-service/src/test/java/cz/muni/fi/pa165/service/PackingServiceTest.java
added PackingFacade, PriceService, MarketingEventistFacadeTest, WineListFacadeTest, PackingServiceTest
> added PackingFacade, PriceService, MarketingEventistFacadeTest, WineListFacadeTest, PackingServiceTest

- wine-cellar-api/src/main/java/cz/muni/fi/pa165/facade/PackingFacade.java
- wine-cellar-persistence/src/main/java/cz/muni/fi/pa165/Main.java
- wine-cellar-persistence/src/main/java/cz/muni/fi/pa165/config/InMemoryDatabaseSpring.java
- wine-cellar-persistence/src/main/java/cz/muni/fi/pa165/config/PersistenceApplicationContext.java
- wine-cellar-persistence/src/main/java/cz/muni/fi/pa165/dao/PackingDao.java
- wine-cellar-persistence/src/main/java/cz/muni/fi/pa165/dao/PackingDaoImpl.java
- wine-cellar-persistence/src/test/java/cz/muni/fi/pa165/dao/MarketingEventDaoTest.java
- wine-cellar-persistence/src/test/java/cz/muni/fi/pa165/dao/PackingDaoTest.java
- wine-cellar-persistence/src/test/java/cz/muni/fi/pa165/dao/PriceDaoTest.java
- wine-cellar-persistence/src/test/java/cz/muni/fi/pa165/dao/WineDaoTest.java
- wine-cellar-persistence/src/test/java/cz/muni/fi/pa165/dao/WineListDaoTest.java
> Edit Dao and tests.

- wine-cellar-api/pom.xml
- wine-cellar-api/src/main/java/cz/muni/fi/pa165/dto/PackingDto.java
- wine-cellar-api/src/main/java/cz/muni/fi/pa165/dto/WineListDto.java
- wine-cellar-api/src/main/java/cz/muni/fi/pa165/facade/MarketingEventFacade.java
- wine-cellar-api/src/main/java/cz/muni/fi/pa165/facade/PriceFacade.java
- wine-cellar-persistence/src/main/java/cz/muni/fi/pa165/dao/PackingDao.java
- wine-cellar-persistence/src/main/java/cz/muni/fi/pa165/dao/WineListDao.java
- wine-cellar-persistence/src/main/java/cz/muni/fi/pa165/dao/WineListDaoImpl.java
- wine-cellar-persistence/src/main/java/cz/muni/fi/pa165/entity/MarketingEvent.java
- wine-cellar-persistence/src/main/java/cz/muni/fi/pa165/entity/Packing.java
- wine-cellar-persistence/src/main/java/cz/muni/fi/pa165/entity/WineList.java
- wine-cellar-service/src/main/java/cz/muni/fi/pa165/facade/PriceFacadeImpl.java
- wine-cellar-service/src/main/java/cz/muni/fi/pa165/service/MarketingEventService.java
- wine-cellar-service/src/main/java/cz/muni/fi/pa165/service/MarketingEventServiceImpl.java
- wine-cellar-service/src/main/java/cz/muni/fi/pa165/service/WineListService.java
- wine-cellar-service/src/main/java/cz/muni/fi/pa165/service/WineListServiceImpl.java
> Refactoring classes

- wine-cellar-api/pom.xml
- wine-cellar-api/src/main/java/cz/muni/fi/pa165/dto/WineDto.java
- wine-cellar-api/src/main/java/cz/muni/fi/pa165/facade/PackingFacade.java
- wine-cellar-service/src/main/java/cz/muni/fi/pa165/service/PriceService.java
> packing facade, priceService

- wine-cellar-service/src/test/java/cz/muni/fi/pa165/service/PackingServiceTest.java
- wine-cellar-service/src/test/java/cz/muni/fi/pa165/service/WineBuilder.java
> WineBuilder added

- wine-cellar-persistence/src/main/java/cz/muni/fi/pa165/dao/WineDao.java
- wine-cellar-persistence/src/main/java/cz/muni/fi/pa165/dao/WineDaoImpl.java
- wine-cellar-service/src/main/java/cz/muni/fi/pa165/service/PriceServiceImpl.java
- wine-cellar-service/src/test/java/cz/muni/fi/pa165/service/PackingServiceTest.java
> WineDao, PriceService updated

- wine-cellar-api/src/main/java/cz/muni/fi/pa165/dto/PackingCreateDto.java
- wine-cellar-api/src/main/java/cz/muni/fi/pa165/facade/PackingFacade.java
- wine-cellar-service/src/main/java/cz/muni/fi/pa165/exception/WineCellarDataAccessException.java
- wine-cellar-service/src/main/java/cz/muni/fi/pa165/facade/PackingFacadeImpl.java
- wine-cellar-service/src/main/java/cz/muni/fi/pa165/service/PriceServiceImpl.java
> packingfacade, priceservice

- wine-cellar-api/src/main/java/cz/muni/fi/pa165/facade/PackingFacade.java
- wine-cellar-persistence/src/main/java/cz/muni/fi/pa165/dao/WineDao.java
- wine-cellar-persistence/src/main/java/cz/muni/fi/pa165/dao/WineDaoImpl.java
- wine-cellar-persistence/src/test/java/cz/muni/fi/pa165/dao/MarketingEventDaoTest.java
- wine-cellar-persistence/src/test/java/cz/muni/fi/pa165/dao/WineDaoTest.java
- wine-cellar-persistence/src/test/java/cz/muni/fi/pa165/dao/WineListDaoTest.java
- wine-cellar-service/src/main/java/cz/muni/fi/pa165/facade/PackingFacadeImpl.java
> names changed

- wine-cellar-persistence/src/main/java/cz/muni/fi/pa165/dao/PriceDao.java
- wine-cellar-persistence/src/test/java/cz/muni/fi/pa165/dao/PriceDaoTest.java
- wine-cellar-service/src/test/java/cz/muni/fi/pa165/service/PackingServiceTest.java
- wine-cellar-service/src/test/java/cz/muni/fi/pa165/service/WineServiceTest.java
> Edit wine service tests.

- wine-cellar-service/src/main/java/cz/muni/fi/pa165/facade/PackingFacadeImpl.java
- wine-cellar-service/src/main/java/cz/muni/fi/pa165/service/WineService.java
- wine-cellar-service/src/main/java/cz/muni/fi/pa165/service/WineServiceImpl.java
- wine-cellar-service/src/test/java/cz/muni/fi/pa165/facade/MarketingEventFacadeTest.java
- wine-cellar-service/src/test/java/cz/muni/fi/pa165/facade/WineListFacadeTest.java
- wine-cellar-service/src/test/java/cz/muni/fi/pa165/service/PackingServiceTest.java
> wineservice, add tests

- wine-cellar-service/src/main/java/cz/muni/fi/pa165/facade/WineListFacadeImpl.java
- wine-cellar-service/src/test/java/cz/muni/fi/pa165/facade/WineListFacadeTest.java
- wine-cellar-service/src/test/java/cz/muni/fi/pa165/service/PriceServiceTest.java
> update test and facade

- wine-cellar-api/src/main/java/cz/muni/fi/pa165/facade/WineListFacade.java
- wine-cellar-persistence/src/main/java/cz/muni/fi/pa165/dao/MarketingEventDaoImpl.java
- wine-cellar-persistence/src/main/java/cz/muni/fi/pa165/dao/PackingDaoImpl.java
- wine-cellar-persistence/src/main/java/cz/muni/fi/pa165/dao/PriceDaoImpl.java
- wine-cellar-persistence/src/main/java/cz/muni/fi/pa165/dao/WineDaoImpl.java
- wine-cellar-persistence/src/main/java/cz/muni/fi/pa165/dao/WineListDaoImpl.java
- wine-cellar-service/src/main/java/cz/muni/fi/pa165/facade/PackingFacadeImpl.java
- wine-cellar-service/src/main/java/cz/muni/fi/pa165/facade/WineListFacadeImpl.java
- wine-cellar-service/src/test/java/cz/muni/fi/pa165/facade/PackingFacadeTest.java
> dao, facade changes

- wine-cellar-api/src/main/java/cz/muni/fi/pa165/dto/WineListCreateDto.java
- wine-cellar-api/src/main/java/cz/muni/fi/pa165/facade/PriceFacade.java
- wine-cellar-persistence/src/main/java/cz/muni/fi/pa165/entity/Price.java
- wine-cellar-service/src/main/java/cz/muni/fi/pa165/facade/MarketingEventFacadeImpl.java
- wine-cellar-service/src/main/java/cz/muni/fi/pa165/facade/PriceFacadeImpl.java
- wine-cellar-service/src/main/java/cz/muni/fi/pa165/facade/WineFacadeImpl.java
- wine-cellar-service/src/main/java/cz/muni/fi/pa165/service/BeanMappingServiceImpl.java
- wine-cellar-service/src/test/java/cz/muni/fi/pa165/facade/PriceFacadeTest.java
- wine-cellar-service/src/test/java/cz/muni/fi/pa165/facade/WineListFacadeTest.java
Fixed PriceFacadeTests, edit facadesImpl
> mb - Edit facade layer III

- wine-cellar-service/src/main/java/cz/muni/fi/pa165/facade/PackingFacadeImpl.java
- wine-cellar-service/src/test/java/cz/muni/fi/pa165/facade/PackingFacadeTest.java
- wine-cellar-spring-mvc/pom.xml
> packing facade update

- wine-cellar-spring-mvc/src/main/java/cz/muni/fi/pa165/config/WebMvcConfig.java
- wine-cellar-spring-mvc/src/main/java/cz/muni/fi/pa165/controller/MarketingEventController.java
- wine-cellar-spring-mvc/src/main/java/cz/muni/fi/pa165/controller/PackingController.java
- wine-cellar-spring-mvc/src/main/java/cz/muni/fi/pa165/controller/PriceController.java
- wine-cellar-spring-mvc/src/main/java/cz/muni/fi/pa165/controller/WineController.java
- wine-cellar-spring-mvc/src/main/java/cz/muni/fi/pa165/controller/WineListController.java
- wine-cellar-spring-mvc/src/main/resources/strings.properties
- wine-cellar-spring-mvc/src/main/resources/strings_cs.properties
- wine-cellar-spring-mvc/src/main/resources/strings_sk.properties
- wine-cellar-spring-mvc/src/main/webapp/WEB-INF/jsp/index.jsp
- wine-cellar-spring-mvc/src/main/webapp/WEB-INF/jsp/winelists/view.jsp
- wine-cellar-spring-mvc/src/main/webapp/WEB-INF/jsp/wines/detail.jsp
- wine-cellar-spring-mvc/src/main/webapp/WEB-INF/jsp/wines/index.jsp
- wine-cellar-spring-mvc/src/main/webapp/WEB-INF/tags/template.tag
wine detail, index, template change
> sb-milestone-3

- wine-cellar-api/src/main/java/cz/muni/fi/pa165/dto/WineCreateDto.java
- wine-cellar-api/src/main/java/cz/muni/fi/pa165/dto/WineUpdateDto.java
- wine-cellar-api/src/main/java/cz/muni/fi/pa165/facade/WineFacade.java
- wine-cellar-service/src/main/java/cz/muni/fi/pa165/facade/WineFacadeImpl.java
- wine-cellar-service/src/test/java/cz/muni/fi/pa165/facade/WineFacadeTest.java
- wine-cellar-spring-mvc/src/main/java/cz/muni/fi/pa165/controller/MarketingEventController.java
- wine-cellar-spring-mvc/src/main/java/cz/muni/fi/pa165/controller/PackingController.java
- wine-cellar-spring-mvc/src/main/java/cz/muni/fi/pa165/controller/PriceController.java
- wine-cellar-spring-mvc/src/main/java/cz/muni/fi/pa165/controller/WineController.java
- wine-cellar-spring-mvc/src/main/java/cz/muni/fi/pa165/controller/WineListController.java
- wine-cellar-spring-mvc/src/main/webapp/WEB-INF/jsp/wines/new.jsp
- wine-cellar-spring-mvc/src/main/webapp/WEB-INF/jsp/wines/update.jsp
Create WineCreateDto, WineUpdateDto, edit create and update wines
> mb-Edit WineController

- wine-cellar-api/src/main/java/cz/muni/fi/pa165/dto/UserCreateDto.java
- wine-cellar-api/src/main/java/cz/muni/fi/pa165/dto/UserDto.java
- wine-cellar-api/src/main/java/cz/muni/fi/pa165/facade/UserFacade.java
- wine-cellar-persistence/src/main/java/cz/muni/fi/pa165/entity/User.java
- wine-cellar-sample-data/src/main/java/cz/muni/fi/pa165/SampleDataLoadingFacadeImpl.java
- wine-cellar-service/src/main/java/cz/muni/fi/pa165/facade/UserFacadeImpl.java
- wine-cellar-service/src/main/java/cz/muni/fi/pa165/service/UserService.java
- wine-cellar-service/src/main/java/cz/muni/fi/pa165/service/UserServiceImpl.java
- wine-cellar-spring-mvc/src/main/java/cz/muni/fi/pa165/config/SecurityConfig.java
- wine-cellar-spring-mvc/src/main/java/cz/muni/fi/pa165/controller/LoginController.java
- wine-cellar-spring-mvc/src/main/java/cz/muni/fi/pa165/initializer/SecurityInitializer.java
- wine-cellar-spring-mvc/src/main/resources/strings.properties
- wine-cellar-spring-mvc/src/main/resources/strings_cs.properties
- wine-cellar-spring-mvc/src/main/resources/strings_sk.properties
- wine-cellar-spring-mvc/src/main/webapp/WEB-INF/jsp/index.jsp
- wine-cellar-spring-mvc/src/main/webapp/WEB-INF/tags/template.tag
> auth login/out ok

- wine-cellar-service/src/main/java/cz/muni/fi/pa165/facade/PriceFacadeImpl.java
- wine-cellar-spring-mvc/src/main/java/cz/muni/fi/pa165/controller/PriceController.java
- wine-cellar-spring-mvc/src/main/java/cz/muni/fi/pa165/controller/WineController.java
- wine-cellar-spring-mvc/src/main/webapp/WEB-INF/jsp/marketingevents/index.jsp
- wine-cellar-spring-mvc/src/main/webapp/WEB-INF/jsp/prices/new.jsp
- wine-cellar-spring-mvc/src/main/webapp/WEB-INF/jsp/prices/update.jsp
- wine-cellar-spring-mvc/src/main/webapp/WEB-INF/jsp/winelists/index.jsp
- wine-cellar-spring-mvc/src/main/webapp/WEB-INF/jsp/winelists/update.jsp
- wine-cellar-spring-mvc/src/main/webapp/WEB-INF/jsp/wines/detail.jsp
- wine-cellar-spring-mvc/src/main/webapp/WEB-INF/jsp/wines/index.jsp
- wine-cellar-spring-mvc/src/main/webapp/WEB-INF/jsp/wines/update.jsp
- wine-cellar-spring-mvc/src/main/webapp/WEB-INF/tags/template.tag
Fixed update Wine, add price to wine
> mb-controllers

- wine-cellar-api/src/main/java/cz/muni/fi/pa165/dto/UserDto.java
- wine-cellar-rest/pom.xml
- wine-cellar-spring-mvc/src/main/java/cz/muni/fi/pa165/controller/LoggedUser.java
- wine-cellar-spring-mvc/src/main/java/cz/muni/fi/pa165/controller/LoginController.java
- wine-cellar-spring-mvc/src/main/java/cz/muni/fi/pa165/controller/MarketingEventController.java
- wine-cellar-spring-mvc/src/main/java/cz/muni/fi/pa165/controller/PriceController.java
- wine-cellar-spring-mvc/src/main/java/cz/muni/fi/pa165/controller/WineController.java
- wine-cellar-spring-mvc/src/main/java/cz/muni/fi/pa165/controller/WineListController.java
- wine-cellar-spring-mvc/src/main/webapp/WEB-INF/jsp/marketingevents/index.jsp
- wine-cellar-spring-mvc/src/main/webapp/WEB-INF/jsp/winelists/index.jsp
- wine-cellar-spring-mvc/src/main/webapp/WEB-INF/jsp/wines/index.jsp
- wine-cellar-spring-mvc/src/main/webapp/WEB-INF/tags/template.tag
> improvement

- wine-cellar-spring-mvc/src/main/java/cz/muni/fi/pa165/controller/MarketingEventController.java
- wine-cellar-spring-mvc/src/main/java/cz/muni/fi/pa165/controller/WineController.java
- wine-cellar-spring-mvc/src/main/webapp/META-INF/context.xml
- wine-cellar-spring-mvc/src/main/webapp/WEB-INF/jsp/marketingevents/index.jsp
- wine-cellar-spring-mvc/src/main/webapp/WEB-INF/jsp/prices/index.jsp
- wine-cellar-spring-mvc/src/main/webapp/WEB-INF/jsp/winelists/index.jsp
- wine-cellar-spring-mvc/src/main/webapp/WEB-INF/jsp/winelists/view.jsp
- wine-cellar-spring-mvc/src/main/webapp/WEB-INF/jsp/wines/index.jsp
> mb-edited-views

- wine-cellar-api/src/main/java/cz/muni/fi/pa165/dto/PackingCreateDto.java
- wine-cellar-spring-mvc/src/main/java/cz/muni/fi/pa165/controller/PriceController.java
- wine-cellar-spring-mvc/src/main/java/cz/muni/fi/pa165/converters/DateConverter.java
- wine-cellar-spring-mvc/src/main/resources/strings.properties
- wine-cellar-spring-mvc/src/main/webapp/WEB-INF/jsp/prices/update.jsp
- wine-cellar-spring-mvc/src/main/webapp/WEB-INF/jsp/winelists/new.jsp
- wine-cellar-spring-mvc/src/main/webapp/WEB-INF/jsp/winelists/update.jsp
datepicker handle wrong format
> datepicker handle wrong format
